name: Secure Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Secret in Workflow
      run: GIT_TOKEN = ${{ secrets.GIT_TOKEN }}"

